name: Docker CD

on:
  push:
    branches:
      - master
    tags:
      - '*'
    paths-ignore:
      - '**.md'

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    
      - name: checkout code
        uses: actions/checkout@v2
    
      - name: Log in to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - if: startsWith(github.ref, 'refs/heads/master')
        run: echo "TAG=latest" >> $GITHUB_ENV
        
      - if: startsWith(github.ref, 'refs/tags')
        run: echo "TAG=$(git describe --tags)" >> $GITHUB_ENV
    
      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          context: ./build
          file: ./build/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.TAG }}